<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ik_dcefrontendediting"
 *
 * Auto generated by Extension Builder 2017-11-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Additions to frontend editing',
    'description' => 'Fixes editing DCE elements on the frontend',
    'category' => 'misc',
    'author' => 'Igor Kruglov, Rainer Karnovski',
    'author_email' => 'igor@buildsite.me',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.5',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
